name: Build and test NodeJS app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  #allow manual run from s tab

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        #specify node version
    
    steps:
    #sequence of task that will be executed during the job
    - uses: actions/checkout@v4
    #WARNING : node16 has reached end of life so some actions version may not be suited for Node latest versions
    
    - name: setup node
      uses: actions/setup-node@v4
      with: 
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run : |
        npm install
        npm ci
        # npm clean install

    - name: build
      run: |
        npm run build --if-present
        npm run test --if-present

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    
    - name: checkout repo
      run: actions/checkout@v4

    - name: set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Get PWD
      run: |
        echo $PWD
        echo ${{ github.workspace }}
        ls -a
        ls -a /home/runner/work/CurriculumAPI

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:latest
    
    - name: Run the image in a container
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo:latest
        run: |
          echo "runing the docker image"
          echo "Testing the nodejs  app endpoints"
            echo ${{ needs.build.outputs.digest }}
