name: Build and test sample NodeJS app

on:
  push:
    branches: [ "feat/sample-app" ]

  workflow_dispatch:
  #allow manual run from s tab

jobs:

  build-node:
  
    runs-on: ubuntu-latest
  
    steps:
    
      - run: echo "This is a simple Node.js application"

      - run: node --version

      - run: npm --version 

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run app
        run: node app.js